### ISSUE TITLE
Date filtering issue

### ISSUE THREAD

**Issue by meh-uk** [openpsa/jsgrid#22]
Taken from [jqGrid #674](https://github.com/tonytomov/jqGrid/issues/674)
newformat is applied in parsedate() even when the date has already been converted. This breaks the filtering of dates when newformat differs from srcformat.

To recreate:
Input is 2014-09-08;
datatype = local; // I assume this is a/the culprit
srcformat = 'Y-m-d';
newformat = 'n/j/Y';
Enable filter toolbar.

The grid shows 9/8/2014, but won't filter correctly because when filtering jqGrid is trying to apply 'Y-m-d' to 9/8/2014.)

**Comment by OlegKi** [comment]
@meh-uk : I'm not sure that it's a bug. Try [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/autoresizeOnDoubleClickOnColumnResizer1.htm). It uses different `srcformat` and `newformat` and it works.

I know many bug reports in working with dates. The problem is wrong usage of date options. I wanted to extend default templates (see [here](https://github.com/OlegKi/jqGrid/blob/master/js/grid.base.js#L180-L191)) with two-three or more additional templates for date. So that one can just include `template: "dateIso"`, `template: "dateTimeIso"`, `template: "dateIsoDatepicker"` and so on. The default `newformat` will be used from the locale file. To implement `template: "dateIsoDatepicker"` one need to extend `newformat` with `jsNewFormat` which use more common use JavaScript/jQuery UI format of date (see [here](http://api.jqueryui.com/datepicker/#utility-formatDate)) instead of PHP date format (see [here](http://php.net/manual/en/function.date.php)). One can look through all existing locale files and to fill the field jsNewFormat` based on `newformat`. I'm sure that there are not so much variants.

I think that one should provide the usage of new `globalize` plugin which will use Unicode CLDR JSON data after the plugin will be final.

**Comment by meh-uk** [comment]
I've reproduced this in a demo.

**Comment by meh-uk** [comment]
Fix merged. Now closing.
