### ISSUE TITLE
Builder notice components

### ISSUE THREAD

**Issue by bouks** [openpsa/jsgrid#89]
It would be cool if the js header comments mention the chosen components in the builder.
So if updates comes, people can remember the components they chose and make the same build.

**Comment by meh-uk** [comment]
Nice idea!

**Comment by smartcorestudio** [comment]
Yes. Also, maybe it's more complicated, but there is one more option: to generate config js file which can be loaded later into download builder (you can see something similar for example in ckeditor http://ckeditor.com/builder or bootstrap http://getbootstrap.com/customize/ build customizers )

**Comment by flack** [comment]
Yes, this is definitely on my todo list. @smartcorestudio: It's not that complicated anymore, because download builder already changes `grid.base.js` before sending it to closure compiler (to inject the chosen default locale), so we have all the logic in place already, we just need to add one more line
